### ISSUE TITLE
One feature that none of the Raspi power hats ever had, food for thought

### ISSUE THREAD

**Issue by tbaumann** [Scally-H/RedReactor#1]
Hi,

I think you are doing a lot well here. A few general thoughts, this is a UPS, there is already generic software for this that has a lot of important smarts built in.
I think it would be good if a Raspi backup power board would support NUT (Network UPS Tools)

The most important UPS style feature that none of the boards I know do support is a shutdown timer. The last thing a Linux (or other) system does when shutting down for empty-battery reasons is, to send the UPS a shut down in X seconds command.
This happens either in the UPS kernel driver near the HALT command or at the latest opportunity from userspace.
The purpose of this is to ensure a reboot. It's a subtle but important requirement. (Some less smart UPS can only switch off immediately, that is mostly safe if the shutoff command is issued in the kernel driver)

Imagine the system shuts down and power is restored while it's shutting down. The result would be that the system halted (or switched off) but the UPS doesn't know this. There will be no switch-on event on when the power is back.

Therefore a UPS would in any case cut the power at the end of the shutdown cycle and then decide based on power status to potentially switch back.

Another level of smartness that a good UPS has is a battery threshold for switching back on. It should ensure it has enough battery charge to manage a complete boot and subsequent shutdown on battery power if power was lost during the boot process while the battery is still empty.

I know the temptation is easy to just assume a battery management chip provides the feature-set of a UPS. And some may actually do this. But no implementation I have seen so far made use of it, INA219 does not.
(I believe some BMS chips do at least have a command to isolate the load)

Just putting this out there in the hope that one day someone will actually make a Raspy UPS that has minimal UPS feature-set.

**Comment by Scally-H** [comment]
Great comments, thanks! Some of the features you mention can be implemented in software, for example, to run a script that delays the shutdown sequence by X seconds and can check the status of external power (and any other controlling inputs) before issuing the shutdown command or not. This could easily accommodate situations where you experience short power outages and want to continue if power resumed within a defined period of time. Once the shutdown is initiated, of course, the Pi will complete it's shutdown, but we showed in a [YouTube video](https://youtu.be/Ob2czPwil8o) how you could create a small circuit to switch the Pi back on when external power is restored. By setting your shutdown battery threshold with some margin you should be able to power up when external power resumes, and shutdown immediately if external power was removed again.
