### ISSUE TITLE
node red error 

### ISSUE THREAD

**Issue by nsk** [Scally-H/RedReactor#2]
Flows stopped due to missing node types.

ui_spacer
ui_group
ui_tab
ui_text
ui_media
ui_gauge
ui_chart
ui_toast
ui_slider
ui_button
ui_template

**Comment by Scally-H** [comment]
The readme file mentions:
The Red Reactor Dashboard is built with nodes from the node-red-dashboard component, which you need to install from within Node Red - go to User Settings / Palette / Install and search for node-red-dashboard. It also uses a media display node, for which you need to install node-red-contrib-ui-media.

Could you please see if this solves your problem?

**Comment by nsk** [comment]
ok  thx! sorry for the mistake
