### ISSUE TITLE
Standoffs

### ISSUE THREAD

**Issue by emersonsc** [Scally-H/RedReactor#4]
The assembly instructions mention standoffs, yet don't mention what size standoffs are needed. They also use the word "provided" but mine came with none. A bit useless if I can't actually attach my pi to this and no specs as to what size are needed.

**Comment by tedserreyn** [comment]
i found mine rolled in the cardboard.i’m not sure how to insert the batteries.  i haven’t had any time to research it yet.Ted SerreynSerreyn Network Services, LLCOn Apr 27, 2023, at 5:29 PM, Emerson Corder ***@***.***> wrote:﻿
The assembly instructions mention standoffs, yet don't mention what size standoffs are needed. They also use the word "provided" but mine came with none. A bit useless if I can't actually attach my pi to this and no specs as to what size are needed.

**Comment by tedserreyn** [comment]
﻿i found mine rolled in the cardboard.i’m not sure how to insert the batteries.  i haven’t had any time to research it yet.Ted SerreynSerreyn Network Services, LLCOn Apr 27, 2023, at 5:29 PM, Emerson Corder ***@***.***> wrote:﻿
The assembly instructions mention standoffs, yet don't mention what size standoffs are needed. They also use the word "provided" but mine came with none. A bit useless if I can't actually attach my pi to this and no specs as to what size are needed.

**Comment by Scally-H** [comment]
Hi @emersonsc - indeed, we have been pretty careful to check that the stand-offs were packaged up as @tedserreyn describes - placed inside the extra cardboard added to stop the board(s) sliding about. Please can you check all packaging provided?

**Comment by Scally-H** [comment]
@tedserreyn on page 3 of the manual is a picture of the battery orientation, with the battery + to match the white highlighted + symbols on the battery holder. There is another picture at [https://www.theredreactor.com/features/](https://www.theredreactor.com/features/) if that is quicker to find.
