### ISSUE TITLE
Making Web Monitor Run at start up

### ISSUE THREAD

**Issue by emersonsc** [Scally-H/RedReactor#8]
Not a issue, but a feature request to have instructions added to have the Web Monitor run as a service or run automatically at start up like the other two add ons.

**Comment by Scally-H** [comment]
Sure - I'll update the GitHub soon. For now, you can re-use the CRON example by changing the paths to RR_WebMonitor.py, though it will run as root and you'll need to install matplotlib with `sudo pip3 install matplotlib` (I checked and this works fine).

**Comment by emersonsc** [comment]
The Pi Zero 2 W did not like running that sudo install, I had to put it in front of the AC to keep it cool so it would complete.

I went the route of the systemd like the other services so, like you said, if there was a failure, it would attempt to reload it.

**Comment by Scally-H** [comment]
A systemd service file (set to run as user 'pi', update as necessary) has been added to RR_WebMonitor, which has also been updated to provide a limited restart/shutdown web page in case of I2C access start-up errors. See the README file for install instructions.

**Comment by emersonsc** [comment]
Awesome I'll check it out, thank you!
